import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "./home.module.css";
import useDummyData from "@/components/dummy_data";
const inter = Inter({ subsets: ["latin"] });

const API = { users: [{ name: "name", age: "range(5, 20)" }] };
export default function Home() {
  const data = useDummyData(API);
  return (
    <>
      <Head>
        <title>Cradle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {JSON.stringify(data)}
      </main>
    </>
  );
}
