import RaisedButton from "@/components/RaisedButton";
import UserRedirect from "@/components/UserRedirect";
import { useAdminDashboardAPI, useUser } from "@/logic/api";
import accountBalanceWallet from "./assets/account_balance_wallet.svg";
import group from "./assets/group.svg";
import hub from "./assets/hub.svg";
import school from "./assets/school.svg";
import spaceDashboard from "./assets/space_dashboard.svg";
import Head from "next/head";
import Table from "@/components/Table";
import Box from "../../components/Box";
import TopRow from "./TopRow";
import FirstRow from "./FirstRow";
import DashboardLayout from "@/components/DashboardLayout";
import MiddleRow from "./MiddleRow";

const ADMIN_TABS = [
  {
    name: "Dashboard",
    icon: spaceDashboard,
  },
  {
    name: "Users",
    icon: group,
  },
  {
    name: "Academic",
    icon: school,
  },
  {
    name: "Financial",
    icon: accountBalanceWallet,
  },
  {
    name: "Communication",
    icon: hub,
  },
];

export default function Admin() {
  const user = useUser();
  return (
    <>
      <Head>
        <title>Cradle - Administator Portal</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <DashboardLayout tabs={ADMIN_TABS}>
        <UserRedirect auth>
          <MainLayout />
        </UserRedirect>
      </DashboardLayout>
    </>
  );
}

const MainLayout = () => {
  return (
    <div className="px-4 py-16 sm:px-8">
      <TopRow />
      <FirstRow />
      <MiddleRow />
    </div>
  );
};
